//////////////////////////////////////////////////////////////////////////////
// Model: blinky.qm
// File:  ./blinky.ino
//
// Modified by : Anky
// ********* To compile on FRAUNCHPAD+Energia platforms ********* 
// Controller : MSP430FR5739
//
// This code has been generated by QM tool (see state-machine.com/qm).
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//////////////////////////////////////////////////////////////////////////////
// @(/2/0) ...................................................................
#include "qp_port.h"
#include "Arduino.h"  // always include in your sketch

Q_DEFINE_THIS_FILE
#define LED RED_LED

using namespace QP;

#define BSP_TICKS_PER_SEC 50
#define MCK           F_CPU //16000000U
#define SMCLK         F_CPU/8 //1100000U
#define F_TIMER       F_CPU/8

enum BlinkySignals { // signals for the Blinky application
    TIMEOUT_SIG = Q_USER_SIG
};

//............................................................................
void BSP_init(void) {
    pinMode(LED, OUTPUT); 
}
//............................................................................
void BSP_ledOff(void) {
    digitalWrite( LED,LOW);
}
//............................................................................
void BSP_ledOn(void) {
    digitalWrite( LED,HIGH);
}
//............................................................................
__attribute__((interrupt(TIMER0_B0_VECTOR)))
void ISRTimer_B (void)
{
    QK_ISR_ENTRY();
    QF::TICK((void *)0); // process all armed time events
    QK_ISR_EXIT();
}
//............................................................................
void QF::onStartup(void) {

  TB0CCTL0 = CCIE;                          // TBCCR0 interrupt enabled
  TB0CCR0 = ((F_TIMER + BSP_TICKS_PER_SEC/2)/BSP_TICKS_PER_SEC)+1;
  TB0CTL = TBSSEL_2 + MC_1 + ID_3;          // SMCLK, continuous up mode
}
//............................................................................
void QF::onCleanup(void) {
}
//............................................................................
void QF::onIdle() {
    QF_INT_ENABLE(); // re-enable interrupts
                     //TODO: Sleep functions
}
//............................................................................
void Q_onAssert(char const Q_ROM * const Q_ROM_VAR file, int line) {
    QF_INT_DISABLE(); // disable all interrupts
    for(;;)
    {
    }
}

//============================================================================
// generate code for the Blinky application...
// @(/1/0) ...................................................................
class Blinky : public QP::QActive {
public:
    QTimeEvt m_timeEvt;

public:
    Blinky()
      : QActive(Q_STATE_CAST(&Blinky::initial)),
        m_timeEvt(TIMEOUT_SIG) 
    {
        // empty
    }

protected:
    static QP::QState initial(Blinky * const me, QP::QEvt const * const e);
    static QP::QState off(Blinky * const me, QP::QEvt const * const e);
    static QP::QState on(Blinky * const me, QP::QEvt const * const e);
};

// @(/1/0) ...................................................................

// @(/1/0/2) .................................................................
// @(/1/0/2/0)
QP::QState Blinky::initial(Blinky * const me, QP::QEvt const * const e) {
    me->m_timeEvt.postEvery(me, BSP_TICKS_PER_SEC);
    return Q_TRAN(&Blinky::off);
}
// @(/1/0/2/1) ...............................................................
QP::QState Blinky::off(Blinky * const me, QP::QEvt const * const e) {
    QP::QState status_;
    switch (e->sig) {
        // @(/1/0/2/1)
        case Q_ENTRY_SIG: {
            BSP_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        // @(/1/0/2/1/0)
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blinky::on);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm::top);
            break;
        }
    }
    return status_;
}
// @(/1/0/2/2) ...............................................................
QP::QState Blinky::on(Blinky * const me, QP::QEvt const * const e) {
    QP::QState status_;
    switch (e->sig) {
        // @(/1/0/2/2)
        case Q_ENTRY_SIG: {
            BSP_ledOn();
            status_ = Q_HANDLED();
            break;
        }
        // @(/1/0/2/2/0)
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blinky::off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm::top);
            break;
        }
    }
    return status_;
}


//............................................................................
static Blinky l_blinky;                           // instantiate the Blinky AO
QActive *AO_Blinky = &l_blinky;     // initialize the global pointer to Blinky

//............................................................................
void setup() {
    BSP_init(); // initialize the BSP
    QF::init(); // initialize the framework and the underlying RT kernel

    static QEvt const *blinky_queueSto[10]; // alocate event queue buffer
    AO_Blinky->start(1, blinky_queueSto, Q_DIM(blinky_queueSto),
                     (void *)0, 0U);        // start the Blinky active object
}

//////////////////////////////////////////////////////////////////////////////
// NOTE1: Do not define the loop() function, because this function is
// already defined in the QP port to Arduino


